import type { RuleCategory, SeverityLevel } from '@/types';

export interface AccessibilityRuleDefinition {
  id: string;
  category: RuleCategory;
  title: string;
  severity: SeverityLevel;
  wcagCriterion: string;
  description: string;
  whyItMatters: string;
  whoIsAffected: string;
  defaultRecommendation: string;
  fixableWithAi: boolean;
}

export const WCAG_ACCESSIBILITY_RULES: AccessibilityRuleDefinition[] = [
  // 1. VISION ACCESSIBILITY RULES (Weight: 20%)
  {
    id: 'VIS-001',
    category: 'vision',
    title: 'Missing Image Alternative (Alt) Text',
    severity: 'critical',
    wcagCriterion: '1.1.1 Non-text Content (Level A)',
    description: 'Images, diagrams, and graphic figures lack machine-readable alternative text descriptions.',
    whyItMatters: 'Screen readers cannot describe non-text elements to blind and low-vision users.',
    whoIsAffected: 'Screen reader users, blind and low-vision individuals',
    defaultRecommendation: 'Provide a concise, factual text alternative describing the meaning and purpose of the visual.',
    fixableWithAi: true,
  },
  {
    id: 'VIS-002',
    category: 'vision',
    title: 'Complex Infographic/Chart Lacks Multi-Tier Narrative',
    severity: 'high',
    wcagCriterion: '1.1.1 Non-text Content (Level A) & 1.4.1 Use of Color',
    description: 'Complex charts, bar graphs, and diagrams lack a detailed text summary and tabular breakdown.',
    whyItMatters: 'Brief alt text is insufficient to convey multi-variable trends, metrics, and comparisons.',
    whoIsAffected: 'Low-vision users, blind users, and cognitive difference readers',
    defaultRecommendation: 'Generate a 3-layer description: concise alt text, detailed breakdown, and plain-language summary.',
    fixableWithAi: true,
  },
  {
    id: 'VIS-003',
    category: 'vision',
    title: 'Insufficient Color Contrast (Text to Background)',
    severity: 'high',
    wcagCriterion: '1.4.3 Contrast (Minimum) (Level AA)',
    description: 'Text elements do not meet the minimum 4.5:1 contrast ratio against their background color.',
    whyItMatters: 'Low-contrast text causes eye strain and is unreadable for people with moderate low vision or color blindness.',
    whoIsAffected: 'People with low vision, color blindness, and elderly readers',
    defaultRecommendation: 'Adjust text or background color to achieve at least 7:1 (AAA) contrast.',
    fixableWithAi: true,
  },
  {
    id: 'VIS-004',
    category: 'vision',
    title: 'Information Conveyed Solely via Color',
    severity: 'medium',
    wcagCriterion: '1.4.1 Use of Color (Level A)',
    description: 'Status (e.g. approved/rejected) or chart categories are differentiated only by color hues.',
    whyItMatters: 'Color-blind users cannot differentiate green/red or blue/purple status indicators.',
    whoIsAffected: 'Individuals with Protanopia, Deuteranopia, or Tritanopia',
    defaultRecommendation: 'Add text labels, icons, or hatching patterns alongside color indicators.',
    fixableWithAi: true,
  },

  // 2. COGNITIVE & READING ACCESSIBILITY RULES (Weight: 20%)
  {
    id: 'COG-001',
    category: 'cognitive',
    title: 'High Reading Complexity (Exceeds Grade 10 Level)',
    severity: 'high',
    wcagCriterion: '3.1.5 Reading Level (Level AAA)',
    description: 'Text requires advanced reading ability with dense jargon and multi-clause sentences.',
    whyItMatters: 'Complex academic language creates severe barriers for people with learning disabilities, dyslexia, or non-native fluency.',
    whoIsAffected: 'People with dyslexia, ADHD, cognitive disabilities, and non-native readers',
    defaultRecommendation: 'Provide a simplified version at a 7th-grade reading level using bulleted takeaways.',
    fixableWithAi: true,
  },
  {
    id: 'COG-002',
    category: 'cognitive',
    title: 'Dense, Unbroken Text Blocks (Cognitive Overload)',
    severity: 'medium',
    wcagCriterion: '1.4.8 Visual Presentation (Level AAA)',
    description: 'Paragraphs contain more than 60 words without subheadings, bullet points, or visual pauses.',
    whyItMatters: 'Dense walls of text cause cognitive fatigue, attention drift, and line-tracking difficulties.',
    whoIsAffected: 'Individuals with ADHD, cognitive differences, and executive functioning challenges',
    defaultRecommendation: 'Break into short paragraphs (max 3-4 lines) with bold anchor keywords and lists.',
    fixableWithAi: true,
  },
  {
    id: 'COG-003',
    category: 'cognitive',
    title: 'Ambiguous or Inconsistent Terminology',
    severity: 'low',
    wcagCriterion: '3.1.4 Abbreviations & 3.2.4 Consistent Identification',
    description: 'Acronyms and specialized terms are used without definitions upon first appearance.',
    whyItMatters: 'Unexplained acronyms confuse readers and impede autonomous comprehension.',
    whoIsAffected: 'All users, especially those with learning disabilities and ESL readers',
    defaultRecommendation: 'Expand abbreviations on first use and provide plain-language explanations.',
    fixableWithAi: true,
  },
  {
    id: 'COG-004',
    category: 'cognitive',
    title: 'Unstructured Action Items / No Step-by-Step Guide',
    severity: 'medium',
    wcagCriterion: '3.3.2 Labels or Instructions (Level A)',
    description: 'Procedures, applications, or next steps are buried in narrative prose instead of an explicit sequential checklist.',
    whyItMatters: 'Users miss deadlines or crucial prerequisites when instructions lack structural clarity.',
    whoIsAffected: 'Individuals with executive function challenges and ADHD',
    defaultRecommendation: 'Extract chronological action items into a numbered step-by-step guide with explicit prerequisites.',
    fixableWithAi: true,
  },

  // 3. HEARING & MULTIMEDIA ACCESSIBILITY RULES (Weight: 15%)
  {
    id: 'HEA-001',
    category: 'hearing',
    title: 'Missing Audio/Video Captions',
    severity: 'critical',
    wcagCriterion: '1.2.2 Captions (Prerecorded) (Level A)',
    description: 'Prerecorded video or multimedia contains dialogue and sound effects without synchronized captions.',
    whyItMatters: 'Deaf and hard of hearing users have no access to spoken speech and audio cues.',
    whoIsAffected: 'Deaf and hard of hearing users',
    defaultRecommendation: 'Generate synchronized WebVTT captions with speaker identification.',
    fixableWithAi: true,
  },
  {
    id: 'HEA-002',
    category: 'hearing',
    title: 'Missing Full Text Transcript for Audio Content',
    severity: 'critical',
    wcagCriterion: '1.2.1 Audio-only and Video-only (Level A)',
    description: 'Podcast, voice recording, or audio stream lacks a verbatim interactive text transcript.',
    whyItMatters: 'Audio-only information cannot be consumed by deaf users or screen reader users in quiet environments.',
    whoIsAffected: 'Deaf, hard-of-hearing, and deaf-blind users',
    defaultRecommendation: 'Generate a timestamped, searchable text transcript with speaker separation.',
    fixableWithAi: true,
  },
  {
    id: 'HEA-003',
    category: 'hearing',
    title: 'Missing Speaker Identification in Dialogue',
    severity: 'medium',
    wcagCriterion: '1.2.2 Captions (Prerecorded) (Level A)',
    description: 'Transcript or captions do not indicate who is speaking during multi-person dialogue.',
    whyItMatters: 'Without speaker tags, users cannot follow conversational context or debate flow.',
    whoIsAffected: 'Deaf and hard of hearing users',
    defaultRecommendation: 'Label speakers (e.g., [Speaker 1], [Interviewer]) across all dialogue turns.',
    fixableWithAi: true,
  },

  // 4. LANGUAGE ACCESSIBILITY RULES (Weight: 15%)
  {
    id: 'LAN-001',
    category: 'language',
    title: 'Missing Primary Document Language Specification',
    severity: 'high',
    wcagCriterion: '3.1.1 Language of Page (Level A)',
    description: 'Document or web page lacks an explicit language attribute (e.g., lang="te" or lang="en").',
    whyItMatters: 'Screen readers cannot switch to correct pronunciation dictionaries, resulting in garbled speech synthesis.',
    whoIsAffected: 'Screen reader users and translation software',
    defaultRecommendation: 'Detect and embed valid ISO language tags (e.g. en, te, hi).',
    fixableWithAi: true,
  },
  {
    id: 'LAN-002',
    category: 'language',
    title: 'Language Barrier / Lack of Regional Translation',
    severity: 'high',
    wcagCriterion: '3.1.2 Language of Parts (Level AA)',
    description: 'Content is available only in English, excluding native regional language speakers (Telugu, Hindi, etc.).',
    whyItMatters: 'Non-English primary language speakers cannot comprehend vital digital services or notices.',
    whoIsAffected: 'Regional language users (Telugu, Hindi, Tamil, Kannada, etc.)',
    defaultRecommendation: 'Generate high-fidelity semantic translation preserving technical hierarchy.',
    fixableWithAi: true,
  },
  {
    id: 'LAN-003',
    category: 'language',
    title: 'Unannounced Multi-lingual Code Switching',
    severity: 'low',
    wcagCriterion: '3.1.2 Language of Parts (Level AA)',
    description: 'Passages in different languages are embedded without declaring span-level language tags.',
    whyItMatters: 'Text-to-speech engines mispronounce foreign phrases when not explicitly tagged.',
    whoIsAffected: 'Screen reader users',
    defaultRecommendation: 'Tag foreign phrases with appropriate language metadata spans.',
    fixableWithAi: true,
  },

  // 5. STRUCTURE & METADATA ACCESSIBILITY RULES (Weight: 15%)
  {
    id: 'STR-001',
    category: 'structure',
    title: 'Missing Heading Hierarchy (H1, H2, H3)',
    severity: 'critical',
    wcagCriterion: '1.3.1 Info and Relationships & 2.4.6 Headings and Labels (Level AA)',
    description: 'Content has visual bold styling instead of semantic heading tags, or skips heading levels (H1 to H4).',
    whyItMatters: 'Screen reader users navigate via heading shortcuts; without true headings, documents are a flat unnavigable stream.',
    whoIsAffected: 'Screen reader users and cognitive navigation users',
    defaultRecommendation: 'Reconstruct structured semantic heading hierarchy (H1 -> H2 -> H3).',
    fixableWithAi: true,
  },
  {
    id: 'STR-002',
    category: 'structure',
    title: 'Scanned Non-Searchable Document (No Text Layer)',
    severity: 'critical',
    wcagCriterion: '1.4.5 Images of Text (Level AA)',
    description: 'Document consists of scanned bitmap images without underlying digital text.',
    whyItMatters: 'Text cannot be selected, searched, enlarged, read aloud, or translated.',
    whoIsAffected: 'All assistive technology users and mobile users',
    defaultRecommendation: 'Perform OCR text extraction and construct digital reading order.',
    fixableWithAi: true,
  },
  {
    id: 'STR-003',
    category: 'structure',
    title: 'Unstructured Data Table Without Column Headers',
    severity: 'high',
    wcagCriterion: '1.3.1 Info and Relationships (Level A)',
    description: 'Tables use layout spaces or lack `<th scope="col">` column header bindings.',
    whyItMatters: 'Screen readers cannot associate data cells with their respective row/column headers.',
    whoIsAffected: 'Screen reader users and low vision users',
    defaultRecommendation: 'Reformat into accessible HTML table with explicit header scopes and narrative caption.',
    fixableWithAi: true,
  },
  {
    id: 'STR-004',
    category: 'structure',
    title: 'Ambiguous Link and Button Text',
    severity: 'medium',
    wcagCriterion: '2.4.4 Link Purpose (In Context) (Level A)',
    description: 'Links use vague anchor text like "click here", "read more", or raw unformatted URLs.',
    whyItMatters: 'Screen reader users listening to link lists out-of-context cannot determine destinations.',
    whoIsAffected: 'Screen reader and voice control users',
    defaultRecommendation: 'Replace with descriptive action text stating destination and purpose.',
    fixableWithAi: true,
  },

  // 6. SCREEN READER COMPATIBILITY RULES (Weight: 15%)
  {
    id: 'SCR-001',
    category: 'screen_reader',
    title: 'Missing Document Landmarks (Main, Nav, Header)',
    severity: 'high',
    wcagCriterion: '1.3.1 Info and Relationships & 2.4.1 Bypass Blocks (Level A)',
    description: 'Document/page structure lacks ARIA landmark regions (main, navigation, complementary).',
    whyItMatters: 'Users cannot quickly jump to the main content or skip repetitive boilerplate.',
    whoIsAffected: 'Screen reader users and keyboard-only navigators',
    defaultRecommendation: 'Structure output with semantic HTML5 elements (`<main>`, `<section>`, `<article>`).',
    fixableWithAi: true,
  },
  {
    id: 'SCR-002',
    category: 'screen_reader',
    title: 'Disrupted Reading Order (Multi-column Confusion)',
    severity: 'high',
    wcagCriterion: '1.3.2 Meaningful Sequence (Level A)',
    description: 'Reading order follows raw visual layout instead of logical programmatic reading sequence.',
    whyItMatters: 'Assistive tech reads across columns horizontally, jumbling sentences and destroying meaning.',
    whoIsAffected: 'Screen reader users and text-to-speech users',
    defaultRecommendation: 'Linearize reading order into top-to-bottom, left-to-right single logical flow.',
    fixableWithAi: true,
  },
  {
    id: 'SCR-003',
    category: 'screen_reader',
    title: 'Decorative Elements Announced as Content',
    severity: 'low',
    wcagCriterion: '1.1.1 Non-text Content (Level A)',
    description: 'Decorative dividers, icons, and background shapes lack `aria-hidden="true"` or empty alt tags.',
    whyItMatters: 'Creates repetitive auditory clutter that slows down navigation.',
    whoIsAffected: 'Screen reader users',
    defaultRecommendation: 'Mark pure visual decorations with `aria-hidden="true"` or `alt=""`.',
    fixableWithAi: true,
  },
];
