import { RuleCategory, SeverityLevel } from '@/types';

export interface AccessibilityRuleDefinition {
  id: string;
  category: RuleCategory;
  title: string;
  severity: SeverityLevel;
  wcagCriterion: string;
  description: string;
  whyItMatters: string;
  whoIsAffected: string;
  defaultRecommendation: string;
  fixableWithAi: boolean;
}

export const WCAG_ACCESSIBILITY_RULES: AccessibilityRuleDefinition[] = [
  // 1. VISION ACCESSIBILITY RULES (Weight: 20%)
  {
    id: 'VIS-001',
    category: 'vision',
    title: 'Missing Image Alternative Text',
    severity: 'critical',
    wcagCriterion: '1.1.1 Non-text Content (Level A)',
    description: 'Images in the content lack meaningful alternative text descriptions.',
    whyItMatters: 'Screen readers cannot convey the visual meaning or data of the image without text alternatives.',
    whoIsAffected: 'Blind users and screen reader users',
    defaultRecommendation: 'Generate contextual AI alt text and detailed descriptions.',
    fixableWithAi: true,
  },
  {
    id: 'VIS-002',
    category: 'vision',
    title: 'Unlabelled Complex Chart or Diagram',
    severity: 'critical',
    wcagCriterion: '1.1.1 Non-text Content (Level A) & 1.3.1 Info and Relationships',
    description: 'Visual chart, graph, or infographic does not contain tabular data or a textual breakdown.',
    whyItMatters: 'Critical data trends and quantitative figures are inaccessible to those who cannot see the graphic.',
    whoIsAffected: 'Blind, low vision, and screen reader users',
    defaultRecommendation: 'Generate a textual data table and narrative summary of chart trends.',
    fixableWithAi: true,
  },
  {
    id: 'VIS-003',
    category: 'vision',
    title: 'Insufficient Color Contrast',
    severity: 'high',
    wcagCriterion: '1.4.3 Contrast (Minimum) (Level AA)',
    description: 'Text or UI element contrast ratio is below the WCAG minimum threshold (4.5:1 for normal text).',
    whyItMatters: 'Low contrast makes reading extremely difficult or fatiguing for low-vision individuals.',
    whoIsAffected: 'Low vision users, older adults, and individuals in bright environments',
    defaultRecommendation: 'Remediate foreground/background colors or provide High Contrast Mode.',
    fixableWithAi: true,
  },
  {
    id: 'VIS-004',
    category: 'vision',
    title: 'Information Conveyed by Color Alone',
    severity: 'high',
    wcagCriterion: '1.4.1 Use of Color (Level A)',
    description: 'Color is used as the only visual means of conveying information, indicating an action, or distinguishing an element.',
    whyItMatters: 'Users with color vision deficiencies cannot perceive differences communicated solely through color shades.',
    whoIsAffected: 'Color blind users (deuteranopia, protanopia, tritanopia)',
    defaultRecommendation: 'Add text labels, distinct icons, or patterned underlines alongside color cues.',
    fixableWithAi: true,
  },
  {
    id: 'VIS-005',
    category: 'vision',
    title: 'Small or Fixed Font Sizing',
    severity: 'medium',
    wcagCriterion: '1.4.4 Resize Text (Level AA)',
    description: 'Document uses very small typography (<12pt) without dynamic text scaling support.',
    whyItMatters: 'Users with low vision cannot scale text without breaking content alignment.',
    whoIsAffected: 'Low vision and elderly readers',
    defaultRecommendation: 'Format into responsive structured text supporting 200% zoom without loss of content.',
    fixableWithAi: true,
  },

  // 2. COGNITIVE & READING ACCESSIBILITY RULES (Weight: 20%)
  {
    id: 'COG-001',
    category: 'cognitive',
    title: 'Excessive Reading Complexity (High Grade Level)',
    severity: 'high',
    wcagCriterion: '3.1.5 Reading Level (Level AAA)',
    description: 'Content requires a reading ability above lower secondary education (Flesch-Kincaid Grade Level > 12).',
    whyItMatters: 'Complex prose, dense syntax, and academic jargon create major comprehension barriers.',
    whoIsAffected: 'Users with cognitive disabilities, learning differences, non-native speakers, and fatigue',
    defaultRecommendation: 'Generate a plain-language version simplified to an 8th-grade reading level.',
    fixableWithAi: true,
  },
  {
    id: 'COG-002',
    category: 'cognitive',
    title: 'Long Unbroken Paragraphs (Wall of Text)',
    severity: 'medium',
    wcagCriterion: '1.4.8 Visual Presentation (Level AAA) & 2.4.10 Section Headings',
    description: 'Paragraphs contain more than 150 words without structural subheadings or bullet points.',
    whyItMatters: 'Unbroken text walls cause cognitive overload and tracking difficulties for dyslexic and ADHD readers.',
    whoIsAffected: 'Users with ADHD, dyslexia, cognitive fatigue, and reading difficulties',
    defaultRecommendation: 'Chunk paragraphs into focused 2-3 sentence blocks and structured bullet lists.',
    fixableWithAi: true,
  },
  {
    id: 'COG-003',
    category: 'cognitive',
    title: 'Unexplained Technical Jargon or Acronyms',
    severity: 'medium',
    wcagCriterion: '3.1.3 Unusual Words & 3.1.4 Abbreviations (Level AAA)',
    description: 'Domain-specific jargon, obscure idioms, or unexplained acronyms are used without definitions.',
    whyItMatters: 'Readers without specialized domain knowledge cannot interpret key insights accurately.',
    whoIsAffected: 'General audience, ESL users, and neurodivergent individuals',
    defaultRecommendation: 'Provide an inline glossary and expand acronyms on first occurrence.',
    fixableWithAi: true,
  },
  {
    id: 'COG-004',
    category: 'cognitive',
    title: 'Missing Executive Summary or Key Takeaways',
    severity: 'low',
    wcagCriterion: '3.1.5 Reading Level (Level AAA)',
    description: 'Lengthy document lacks an upfront executive summary or key bullet points.',
    whyItMatters: 'Readers struggle to anchor context before reading complex multi-page materials.',
    whoIsAffected: 'Readers with cognitive disabilities and executive function challenges',
    defaultRecommendation: 'Generate an upfront 3-point accessible summary.',
    fixableWithAi: true,
  },

  // 3. HEARING ACCESSIBILITY RULES (Weight: 15%)
  {
    id: 'HEA-001',
    category: 'hearing',
    title: 'Missing Audio/Video Captions',
    severity: 'critical',
    wcagCriterion: '1.2.2 Captions (Prerecorded) (Level A)',
    description: 'Prerecorded video or multimedia contains dialogue and sound effects without synchronized captions.',
    whyItMatters: 'Deaf and hard of hearing users have no access to spoken speech and audio cues.',
    whoIsAffected: 'Deaf and hard of hearing users',
    defaultRecommendation: 'Generate synchronized WebVTT captions with speaker identification.',
    fixableWithAi: true,
  },
  {
    id: 'HEA-002',
    category: 'hearing',
    title: 'Missing Full Text Transcript for Audio Content',
    severity: 'critical',
    wcagCriterion: '1.2.1 Audio-only and Video-only (Level A)',
    description: 'Podcast, voice recording, or audio stream lacks a verbatim interactive text transcript.',
    whyItMatters: 'Audio-only information cannot be consumed by deaf users or screen reader users in quiet environments.',
    whoIsAffected: 'Deaf, hard-of-hearing, and deaf-blind users',
    defaultRecommendation: 'Generate a timestamped, searchable text transcript with speaker separation.',
    fixableWithAi: true,
  },
  {
    id: 'HEA-003',
    category: 'hearing',
    title: 'Missing Speaker Identification in Dialogue',
    severity: 'medium',
    wcagCriterion: '1.2.2 Captions (Prerecorded) (Level A)',
    description: 'Transcript or captions do not indicate who is speaking during multi-person dialogue.',
    whyItMatters: 'Without speaker tags, users cannot follow conversational context or debate flow.',
    whoIsAffected: 'Deaf and hard of hearing users',
    defaultRecommendation: 'Label speakers (e.g., [Speaker 1], [Interviewer]) across all dialogue turns.',
    fixableWithAi: true,
  },

  // 4. LANGUAGE ACCESSIBILITY RULES (Weight: 15%)
  {
    id: 'LAN-001',
    category: 'language',
    title: 'Missing Primary Document Language Specification',
    severity: 'high',
    wcagCriterion: '3.1.1 Language of Page (Level A)',
    description: 'Document or web page lacks an explicit language attribute (e.g., lang="te" or lang="en").',
    whyItMatters: 'Screen readers cannot switch to correct pronunciation dictionaries, resulting in garbled speech synthesis.',
    whoIsAffected: 'Screen reader users and translation software',
    defaultRecommendation: 'Detect and embed valid ISO language tags (e.g. en, te, hi).',
    fixableWithAi: true,
  },
  {
    id: 'LAN-002',
    category: 'language',
    title: 'Language Barrier / Lack of Regional Translation',
    severity: 'high',
    wcagCriterion: '3.1.2 Language of Parts (Level AA)',
    description: 'Content is available only in English, excluding native regional language speakers (Telugu, Hindi, etc.).',
    whyItMatters: 'Non-English primary language speakers cannot comprehend vital digital services or notices.',
    whoIsAffected: 'Regional language users (Telugu, Hindi, Tamil, Kannada, etc.)',
    defaultRecommendation: 'Generate high-fidelity semantic translation preserving technical hierarchy.',
    fixableWithAi: true,
  },
  {
    id: 'LAN-003',
    category: 'language',
    title: 'Unannounced Multi-lingual Code Switching',
    severity: 'low',
    wcagCriterion: '3.1.2 Language of Parts (Level AA)',
    description: 'Passages in different languages are embedded without declaring span-level language tags.',
    whyItMatters: 'Text-to-speech engines mispronounce foreign phrases when not explicitly tagged.',
    whoIsAffected: 'Screen reader users',
    defaultRecommendation: 'Tag foreign phrases with appropriate language metadata spans.',
    fixableWithAi: true,
  },

  // 5. STRUCTURE & METADATA ACCESSIBILITY RULES (Weight: 15%)
  {
    id: 'STR-001',
    category: 'structure',
    title: 'Missing Heading Hierarchy (H1, H2, H3)',
    severity: 'critical',
    wcagCriterion: '1.3.1 Info and Relationships & 2.4.6 Headings and Labels (Level AA)',
    description: 'Content has visual bold styling instead of semantic heading tags, or skips heading levels (H1 to H4).',
    whyItMatters: 'Screen reader users navigate via heading shortcuts; without true headings, documents are a flat unnavigable stream.',
    whoIsAffected: 'Screen reader users and cognitive navigation users',
    defaultRecommendation: 'Reconstruct structured semantic heading hierarchy (H1 -> H2 -> H3).',
    fixableWithAi: true,
  },
  {
    id: 'STR-002',
    category: 'structure',
    title: 'Scanned Non-Searchable Document (No Text Layer)',
    severity: 'critical',
    wcagCriterion: '1.4.5 Images of Text (Level AA)',
    description: 'Document consists of scanned bitmap images without underlying digital text.',
    whyItMatters: 'Text cannot be selected, searched, enlarged, read aloud, or translated.',
    whoIsAffected: 'All assistive technology users and mobile users',
    defaultRecommendation: 'Perform OCR text extraction and construct digital reading order.',
    fixableWithAi: true,
  },
  {
    id: 'STR-003',
    category: 'structure',
    title: 'Unstructured Data Table Without Column Headers',
    severity: 'high',
    wcagCriterion: '1.3.1 Info and Relationships (Level A)',
    description: 'Tables use layout spaces or lack `<th scope="col">` column header bindings.',
    whyItMatters: 'Screen readers cannot associate data cells with their respective row/column headers.',
    whoIsAffected: 'Screen reader users and low vision users',
    defaultRecommendation: 'Reformat into accessible HTML table with explicit header scopes and narrative caption.',
    fixableWithAi: true,
  },
  {
    id: 'STR-004',
    category: 'structure',
    title: 'Ambiguous Link and Button Text',
    severity: 'medium',
    wcagCriterion: '2.4.4 Link Purpose (In Context) (Level A)',
    description: 'Links use vague anchor text like "click here", "read more", or raw unformatted URLs.',
    whyItMatters: 'Screen reader users listening to link lists out-of-context cannot determine destinations.',
    whoIsAffected: 'Screen reader and voice control users',
    defaultRecommendation: 'Replace with descriptive action text stating destination and purpose.',
    fixableWithAi: true,
  },

  // 6. SCREEN READER COMPATIBILITY RULES (Weight: 15%)
  {
    id: 'SCR-001',
    category: 'screen_reader',
    title: 'Missing Document Landmarks (Main, Nav, Header)',
    severity: 'high',
    wcagCriterion: '1.3.1 Info and Relationships & 2.4.1 Bypass Blocks (Level A)',
    description: 'Document/page structure lacks ARIA landmark regions (main, navigation, complementary).',
    whyItMatters: 'Users cannot quickly jump to the main content or skip repetitive boilerplate.',
    whoIsAffected: 'Screen reader users and keyboard-only navigators',
    defaultRecommendation: 'Structure output with semantic HTML5 elements (`<main>`, `<section>`, `<article>`).',
    fixableWithAi: true,
  },
  {
    id: 'SCR-002',
    category: 'screen_reader',
    title: 'Disrupted Reading Order (Multi-column Confusion)',
    severity: 'high',
    wcagCriterion: '1.3.2 Meaningful Sequence (Level A)',
    description: 'Reading order follows raw visual layout instead of logical programmatic reading sequence.',
    whyItMatters: 'Assistive tech reads across columns horizontally, jumbling sentences and destroying meaning.',
    whoIsAffected: 'Screen reader users and text-to-speech users',
    defaultRecommendation: 'Linearize reading order into top-to-bottom, left-to-right single logical flow.',
    fixableWithAi: true,
  },
  {
    id: 'SCR-003',
    category: 'screen_reader',
    title: 'Decorative Elements Announced as Content',
    severity: 'low',
    wcagCriterion: '1.1.1 Non-text Content (Level A)',
    description: 'Decorative dividers, icons, and background shapes lack `aria-hidden="true"` or empty alt tags.',
    whyItMatters: 'Creates repetitive auditory clutter that slows down navigation.',
    whoIsAffected: 'Screen reader users',
    defaultRecommendation: 'Mark pure visual decorations with `aria-hidden="true"` or `alt=""`.',
    fixableWithAi: true,
  },
];
